var ContainerBridgeConfig = {
    debug: true,
    wechatJsUrl: "http://res.wx.qq.com/open/js/jweixin-1.2.0.js",
    wechatSignatureApiUrl: "http://mp.caiyunlife.com/wechat/AdvanceApi/JsApiSignature",
    wechatAppID: "wx1fed040d52138883",
    wechatAppSecret: "4123a53c249d041901c2c4a85e188fb0",
    wechatAPIList: [
        "onMenuShareTimeline",
        "onMenuShareAppMessage",
        "onMenuShareQQ",
        "onMenuShareWeibo",
        "onMenuShareQZone",
        "startRecord",
        "stopRecord",
        "onVoiceRecordEnd",
        "playVoice",
        "pauseVoice",
        "stopVoice",
        "onVoicePlayEnd",
        "uploadVoice",
        "downloadVoice",
        "chooseImage",
        "previewImage",
        "uploadImage",
        "downloadImage",
        "translateVoice",
        "getNetworkType",
        "openLocation",
        "getLocation",
        "hideOptionMenu",
        "showOptionMenu",
        "hideMenuItems",
        "showMenuItems",
        "hideAllNonBaseMenuItem",
        "showAllNonBaseMenuItem",
        "closeWindow",
        "scanQRCode",
        "chooseWXPay",
        "openProductSpecificView",
        "addCard",
        "chooseCard",
        "openCard"
    ],
    alipayJsUrl: "http://static.alipay.com/aliBridge/1.0.0/aliBridge.min.js",
    relJsUrl: "https://imapi.icbc.com.cn/icbc/jsrel1.0.9.js",
    relAppID: "",
    relSignatureApiUrl: "http://center.elink.yibalian.cn/api/B2EF3A08C1624FF5A78768DD49461C91/JsApi/Signature"
};